### ISSUE TITLE
Library not loaded: @rpath/libproj.13.dylib

### ISSUE THREAD

**Issue by vvoovv** [JeremyBYU/bpyproj#17]
The "from bpyproj.projection import GeneralProjection” fails with a missing libproj library:

Traceback (most recent call last):
 File "<blender_console>", line 1, in <module>
 File "/Users/username/Library/Application Support/Blender/2.82/scripts/addons/bpyproj/projection/__init__.py", line 20, in <module>
 from pyproj import Proj
 File "/Users/username/Library/Application Support/Blender/2.82/scripts/addons/bpyproj/dependencies/binaries/osx_64_37/site-packages/pyproj/__init__.py", line 51, in <module>
 from pyproj import _proj
ImportError: dlopen(/Users/username/Library/Application Support/Blender/2.82/scripts/addons/bpyproj/dependencies/binaries/osx_64_37/site-packages/pyproj/_proj.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libproj.13.dylib
 Referenced from: /Users/username/Library/Application Support/Blender/2.82/scripts/addons/bpyproj/dependencies/binaries/osx_64_37/site-packages/pyproj/_proj.cpython-37m-darwin.so
 Reason: image not found

**Comment by vvoovv** [comment]
@JeremyBYU can you reproduce this error on Mac?

Do you have an idea why it happens on Mac?

**Comment by vvoovv** [comment]
Execute the following commands in the Blender Python Console to reproduce the problem:
```python
from bpyproj.projection import GeneralProjection
```
